name = "ghi-backend"
main = "src/index.ts"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# DATABASE_URL and JWT_SECRET should be set via secrets
JWT_SECRET = "change-me-later"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "2c3d595f50c14b81a7ac44cb52a5d40a"

[triggers]
crons = ["0 */6 * * *"]

[observability]
enabled = true
