name = "ghi-backend"
main = "app/main.py"
compatibility_date = "2024-04-01"
compatibility_flags = ["python_workers"]

[vars]
# We will use Hyperdrive to connect to Neon
# You will set the DATABASE_URL secret using 'wrangler secret put DATABASE_URL'
# Or via the Cloudflare Dashboard.

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "2c3d595f50c14b81a7ac44cb52a5d40a"
